/**
 * ZeR0CyB3r Study Hub // Master Repository Dataset
 * Curated practical resources across Courses, Tools, Hardened Operating Systems, and Field Manuals
 */

var CYBER_COURSES = [
  {
    id: "course-soc-analyst",
    title: "Complete SOC Analyst Training (L1 to L2)",
    badgeText: "BLUE TEAM MASTERCLASS",
    icon: "fa-shield-halved",
    desc: "Comprehensive curriculum covering SIEM alerts monitoring, Splunk search syntax (SPL), phishing email investigation, IOC analysis, and incident escalation workflows.",
    tags: ["SOC L1/L2", "Splunk SIEM", "Incident Triage", "Phishing Analysis", "MITRE ATT&CK"],
    actionUrl: "https://www.youtube.com/results?search_query=soc+analyst+full+course+hands+on",
    actionText: "Watch SOC Series",
    level: "Beginner to Intermediate",
    details: "Covers practical log correlation, Windows Event IDs (4624, 4625, 4688, 7045), VirusTotal and AbuseIPDB reputation lookups, and documented incident containment playbooks."
  },
  {
    id: "course-practical-ethical-hacking",
    title: "Practical Ethical Hacking & Penetration Testing",
    badgeText: "RED TEAM CORE",
    icon: "fa-user-ninja",
    desc: "Hands-on penetration testing roadmap: reconnaissance, network scanning, exploitation, Active Directory attacks, web application assessment, and professional report writing.",
    tags: ["Penetration Testing", "Active Directory", "Network Recon", "Exploitation", "OSCP Prep"],
    actionUrl: "https://www.youtube.com/results?search_query=practical+ethical+hacking+full+course",
    actionText: "Watch Pentest Course",
    level: "All Levels",
    details: "Follows real-world penetration test workflows based on the PTES methodology with live lab setups in VirtualBox and VMware."
  },
  {
    id: "course-portswigger-web-academy",
    title: "PortSwigger Web Security Academy Labs",
    badgeText: "WEB APPLICATION VAPT",
    icon: "fa-spider",
    desc: "Free interactive lab training from the makers of Burp Suite. Master SQL injection, Cross-Site Scripting (XSS), CSRF, SSRF, IDOR, XML External Entity (XXE), and OAuth bypasses.",
    tags: ["Web Security", "OWASP Top 10", "Burp Suite", "SQLi", "XSS", "SSRF"],
    actionUrl: "https://portswigger.net/web-security",
    actionText: "Open PortSwigger Academy",
    level: "Beginner to Advanced",
    details: "Contains hundreds of practical sandbox labs ranging from Apprentice to Practitioner and Mystery lab challenges."
  },
  {
    id: "course-wireshark-deep-dive",
    title: "Wireshark Packet Analysis Masterclass",
    badgeText: "TRAFFIC & FORENSICS",
    icon: "fa-network-wired",
    desc: "Learn to analyze raw packet captures (PCAP), identify TCP three-way handshake anomalies, decrypt SSL/TLS sessions using (pre)-master secrets, and detect C2 beacon traffic.",
    tags: ["Wireshark", "Network Analysis", "PCAP Forensics", "TCP/IP", "TLS Decryption"],
    actionUrl: "https://www.youtube.com/results?search_query=wireshark+packet+analysis+masterclass",
    actionText: "Watch Wireshark Class",
    level: "All Levels",
    details: "Features hands-on packet dissection exercises with real sample PCAP files containing malware infections, port scans, and DDoS traffic."
  },
  {
    id: "course-active-directory-attacks",
    title: "Active Directory Attacks & Defense Masterclass",
    badgeText: "ENTERPRISE PRIV ESC",
    icon: "fa-diagram-project",
    desc: "Deep dive into enterprise Active Directory architecture: Kerberoasting, AS-REP Roasting, Pass-the-Hash, DCSync, Golden/Silver tickets, and domain privilege escalation.",
    tags: ["Active Directory", "Kerberos", "BloodHound", "Mimikatz", "Lateral Movement"],
    actionUrl: "https://www.youtube.com/results?search_query=active+directory+penetration+testing+course",
    actionText: "Watch AD Pentest Series",
    level: "Intermediate to Advanced",
    details: "Detailed breakdown of the Microsoft Kerberos authentication protocol and how attackers exploit legacy configurations to achieve Domain Admin."
  },
  {
    id: "course-linux-privesc",
    title: "Linux Privilege Escalation for OSCP",
    badgeText: "SYSTEM PRIV ESC",
    icon: "fa-terminal",
    desc: "Systematic local enumeration and exploitation techniques: SUID/SGID binaries, misconfigured sudo permissions, cron job hijacking, capabilities, and kernel exploits.",
    tags: ["Linux PrivEsc", "OSCP", "SUID", "Cron Jobs", "Kernel Exploits", "LinPEAS"],
    actionUrl: "https://www.youtube.com/results?search_query=linux+privilege+escalation+for+oscp",
    actionText: "Watch Linux PrivEsc",
    level: "Intermediate",
    details: "Practical guide to auditing permissions using LinPEAS, manual enumeration scripts, and executing privilege escalation vectors safely."
  },
  {
    id: "course-windows-privesc",
    title: "Windows Privilege Escalation for OSCP",
    badgeText: "WINDOWS PRIV ESC",
    icon: "fa-windows",
    desc: "Master Windows local privilege escalation: unquoted service paths, DLL hijacking, AlwaysInstallElevated, token impersonation (SeImpersonatePrivilege), and registry abuse.",
    tags: ["Windows PrivEsc", "OSCP", "Unquoted Paths", "Token Abuse", "WinPEAS"],
    actionUrl: "https://www.youtube.com/results?search_query=windows+privilege+escalation+for+oscp",
    actionText: "Watch Windows PrivEsc",
    level: "Intermediate",
    details: "Demonstrates JuicyPotato, PrintSpoofer, GodPotato, and manual registry inspection in modern Windows 10 and Server 2022 environments."
  },
  {
    id: "course-malware-analysis",
    title: "Malware Analysis & Reverse Engineering Fundamentals",
    badgeText: "REVERSE ENGINEERING",
    icon: "fa-bug",
    desc: "Learn safe static and dynamic analysis workflows inside isolated REMnux/Flare VM sandboxes using Ghidra, Cutter, x64dbg, PEStudio, ProcMon, and Wireshark.",
    tags: ["Malware Analysis", "Ghidra", "x64dbg", "PE Headers", "Static Analysis", "REMnux"],
    actionUrl: "https://www.youtube.com/results?search_query=practical+malware+analysis+full+course",
    actionText: "Watch Malware Series",
    level: "Intermediate to Advanced",
    details: "Step-by-step disassembly of Portable Executable (PE) binaries, unpacking techniques, dynamic API tracing, and identifying command-and-control callback domains."
  },
  {
    id: "course-bug-bounty",
    title: "Bug Bounty Hunting & Web Recon Pipelines",
    badgeText: "VULNERABILITY RESEARCH",
    icon: "fa-bullseye",
    desc: "Methodologies from top bug bounty researchers: subdomain discovery pipelines, parameter fuzzing, mass DNS resolution, IDOR discovery, and professional report writing.",
    tags: ["Bug Bounty", "Subdomain Recon", "IDOR", "HackerOne", "Bugcrowd", "Nuclei"],
    actionUrl: "https://www.youtube.com/results?search_query=bug+bounty+methodology+full+course",
    actionText: "Watch Bug Bounty Guides",
    level: "All Levels",
    details: "Learn how to build automated asset discovery scripts and approach private bug bounty scopes with methodical precision."
  },
  {
    id: "course-cloud-security",
    title: "Cloud Security & DevSecOps (AWS / Azure)",
    badgeText: "CLOUD ARCHITECTURE",
    icon: "fa-cloud",
    desc: "Cloud security posture management, AWS IAM misconfiguration auditing, S3 bucket exposure, Azure Active Directory privilege escalation, and container security with Docker/K8s.",
    tags: ["Cloud Security", "AWS IAM", "Azure AD", "Docker", "Kubernetes", "DevSecOps"],
    actionUrl: "https://www.youtube.com/results?search_query=aws+cloud+security+hands+on+course",
    actionText: "Watch Cloud Security",
    level: "Intermediate",
    details: "Audit cloud environments using ScoutSuite, Prowler, and Pacu. Learn principle of least privilege and immutable infrastructure deployment."
  },
  {
    id: "course-dfir-incident-response",
    title: "Digital Forensics & Incident Response (DFIR)",
    badgeText: "INCIDENT TRIAGE",
    icon: "fa-magnifying-glass-chart",
    desc: "Incident handling and forensic artifact collection: memory triage with Volatility 3, disk imaging with FTK Imager, timeline reconstruction, and MFT analysis.",
    tags: ["DFIR", "Volatility", "FTK Imager", "Memory Forensics", "Timeline Analysis"],
    actionUrl: "https://www.youtube.com/results?search_query=digital+forensics+incident+response+training",
    actionText: "Watch DFIR Course",
    level: "Intermediate to Advanced",
    details: "Walkthrough real compromise scenarios, dump memory from active malware processes, and create legal-grade evidentiary reports."
  },
  {
    id: "course-red-team-ops",
    title: "Red Team Operations & Adversary Emulation",
    badgeText: "ELITE OPERATIONS",
    icon: "fa-crosshairs",
    desc: "Adversary simulation based on the MITRE ATT&CK framework: building C2 infrastructure, payload generation, AMSI bypass, process hollowing, and living-off-the-land binaries (LOLBAS).",
    tags: ["Red Team", "C2 Frameworks", "LOLBAS", "AMSI Bypass", "Evasion", "Cobalt Strike"],
    actionUrl: "https://www.youtube.com/results?search_query=red+team+operations+training+full",
    actionText: "Watch Red Team Ops",
    level: "Advanced",
    details: "Covers multi-stage redirectors, malleable C2 profiles, evasive shellcode execution, and OPSEC rules of engagement."
  }
];

var CYBER_TOOLS = [
  {
    id: "tool-nmap",
    name: "Nmap Network Mapper & NSE",
    domain: "RECONNAISSANCE",
    icon: "fa-radar",
    desc: "The premier network discovery and security vulnerability scanner. Inspect open ports, running services, OS fingerprints, and execute Lua-based Nmap Scripting Engine (NSE) modules.",
    command: "nmap -sC -sV -p- -T4 -oA target_scan 192.168.1.1",
    tags: ["Port Scanning", "NSE Scripts", "Host Discovery", "Service Fingerprint"],
    officialUrl: "https://nmap.org/download.html",
    actionText: "Download Nmap",
    level: "Essential / All Levels",
    details: "The bedrock utility of every security audit. Features hundreds of NSE scripts for vulnerability detection (vuln, default, auth, safe)."
  },
  {
    id: "tool-burp",
    name: "Burp Suite Community & Pro",
    domain: "WEB APPLICATION VAPT",
    icon: "fa-spider",
    desc: "The industry standard web application security audit suite. Includes HTTP/S intercepting proxy, repeater, decoder, comparer, intruder, and extensible BApp Store plugins.",
    command: "Proxy 127.0.0.1:8080 • CA Certificate installed in browser",
    tags: ["Web Proxy", "OWASP Top 10", "Burp Suite", "PortSwigger", "Repeater"],
    officialUrl: "https://portswigger.net/burp/communitydownload",
    actionText: "Download Burp Suite",
    level: "Beginner to Pro",
    details: "Used by penetration testers worldwide to discover SQLi, XSS, CSRF, SSRF, IDOR, and authentication bypass vulnerabilities."
  },
  {
    id: "tool-wireshark",
    name: "Wireshark Packet Analyzer",
    domain: "NETWORK FORENSICS",
    icon: "fa-network-wired",
    desc: "The world's most widely used network protocol analyzer. Captures real-time packet traffic, analyzes TCP streams, and isolates anomalous communications.",
    command: "wireshark -k -i eth0 -Y 'http.request.method == POST'",
    tags: ["PCAP Analysis", "TCP/IP Inspection", "Protocol Decryption", "SOC Analysis"],
    officialUrl: "https://www.wireshark.org/download.html",
    actionText: "Download Wireshark",
    level: "All Levels",
    details: "Provides deep inspection of hundreds of protocols, live capture, offline analysis, coloring rules, and rich export formats."
  },
  {
    id: "tool-metasploit",
    name: "Metasploit Framework",
    domain: "EXPLOITATION ENGINE",
    icon: "fa-crosshairs",
    desc: "The world's most widely used penetration testing framework. Verify vulnerabilities, manage payloads, and perform post-exploitation audits with Meterpreter.",
    command: "msfconsole -q",
    tags: ["Exploit DB", "Meterpreter", "Post Exploitation", "Payload Generation"],
    officialUrl: "https://www.metasploit.com/",
    actionText: "Get Metasploit",
    level: "Intermediate",
    details: "Features over 2,000+ verified exploit modules, auxiliary scanners, encoders, and multi-platform shellcode staging."
  },
  {
    id: "tool-ghidra",
    name: "Ghidra SRE (NSA)",
    domain: "REVERSE ENGINEERING",
    icon: "fa-microchip",
    desc: "National Security Agency's open-source Software Reverse Engineering framework. Decompiles x86, ARM, MIPS, and executes binary disassembling.",
    command: "ghidraRun",
    tags: ["NSA Toolkit", "Binary Disassembler", "Decompiler", "Malware Analysis"],
    officialUrl: "https://ghidra-sre.org/",
    actionText: "Download Ghidra",
    level: "Advanced",
    details: "Features a rich GUI, automated code analysis, symbol management, headless script execution, and multi-processor architecture support."
  },
  {
    id: "tool-hashcat",
    name: "Hashcat Password Recovery",
    domain: "PASSWORD CRACKING",
    icon: "fa-key",
    desc: "World's fastest GPU-based rule cracking engine supporting over 300+ hash types including NTLM, MD5, SHA-256, Kerberos 5, and bcrypt.",
    command: "hashcat -m 1000 -a 0 ntlm_hashes.txt rockyou.txt",
    tags: ["GPU Cracking", "Rule-based Attack", "NTLM / Kerberos", "Wordlists"],
    officialUrl: "https://hashcat.net/hashcat/",
    actionText: "Download Hashcat",
    level: "Intermediate",
    details: "Utilizes OpenCL and CUDA to achieve billions of hash comparisons per second on modern graphics hardware."
  },
  {
    id: "tool-john",
    name: "John the Ripper (JtR)",
    domain: "PASSWORD AUDIT",
    icon: "fa-unlock-keyhole",
    desc: "Fast and flexible password cracker designed for Unix shadow files, zip/rar archives, SSH private keys, and custom hashes.",
    command: "john --wordlist=/usr/share/wordlists/rockyou.txt hashes.txt",
    tags: ["Password Cracking", "Shadow Hashes", "Cheatsheet", "Wordlist"],
    officialUrl: "https://www.openwall.com/john/",
    actionText: "Download JtR",
    level: "Beginner to Pro",
    details: "Includes helper utilities like zip2john, rar2john, and ssh2john for extracting crackable hash formats."
  },
  {
    id: "tool-sqlmap",
    name: "SQLmap Automated Injection Engine",
    domain: "DATABASE TAKEOVER",
    icon: "fa-database",
    desc: "Automatic SQL injection and database takeover tool. Detects and exploits SQL injection flaws, dumps tables, and spawns OS shell sessions.",
    command: "sqlmap -u 'http://target.com/page.php?id=1' --batch --dbs",
    tags: ["SQL Injection", "Database Dump", "Automated VAPT", "Shell Spawn"],
    officialUrl: "https://sqlmap.org/",
    actionText: "Download SQLmap",
    level: "Intermediate",
    details: "Supports MySQL, Oracle, PostgreSQL, Microsoft SQL Server, SQLite, and 30+ other database management systems."
  },
  {
    id: "tool-bloodhound",
    name: "BloodHound & SharpHound",
    domain: "ACTIVE DIRECTORY",
    icon: "fa-diagram-project",
    desc: "Graph-theory visualization tool used to uncover hidden relationships and attack paths within complex Microsoft Active Directory environments.",
    command: "SharpHound.exe -c All --zipfilename ad_collection.zip",
    tags: ["Active Directory", "Graph Theory", "Kerberoasting", "Privilege Paths"],
    officialUrl: "https://github.com/BloodHoundAD/BloodHound",
    actionText: "BloodHound Repo",
    level: "Intermediate / Advanced",
    details: "Reveals direct and indirect paths to Domain Admin status by analyzing ACLs, Group Memberships, and Active User Sessions."
  },
  {
    id: "tool-gobuster",
    name: "Gobuster Directory & DNS Bruteforcer",
    domain: "CONTENT ENUMERATION",
    icon: "fa-folder-tree",
    desc: "High-performance URL directory, DNS subdomain, vhost, and S3 bucket brute-forcer written in Go for speed and concurrency.",
    command: "gobuster dir -u http://target.com -w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt -t 40",
    tags: ["Directory Bruteforce", "DNS Fuzzing", "Go Language", "Reconnaissance"],
    officialUrl: "https://github.com/OJ/gobuster",
    actionText: "Gobuster Repo",
    level: "All Levels",
    details: "Extremely fast multi-threaded execution with support for custom status codes, extensions (-x php,html,txt), and proxy chaining."
  },
  {
    id: "tool-hydra",
    name: "THC-Hydra Network Logon Cracker",
    domain: "AUTHENTICATION AUDIT",
    icon: "fa-fingerprint",
    desc: "Very fast network logon cracker supporting SSH, FTP, HTTP-POST-FORM, SMB, RDP, MySQL, Telnet, and over 50 other protocols.",
    command: "hydra -l admin -P rockyou.txt 192.168.1.100 ssh",
    tags: ["Online Bruteforce", "SSH Cracker", "Authentication Audit", "THC"],
    officialUrl: "https://github.com/vanhauser-thc/thc-hydra",
    actionText: "Hydra Repo",
    level: "Intermediate",
    details: "Supports SSL/TLS wrapping, parallel threading (-t 16), and custom form input mappings."
  },
  {
    id: "tool-mimikatz",
    name: "Mimikatz Credential Dumper",
    domain: "WINDOWS POST-EXPLOITATION",
    icon: "fa-shield-halved",
    desc: "Legendary post-exploitation tool created by Benjamin Delpy that extracts plaintext passwords, hash digests, PIN codes, and Kerberos tickets from LSASS memory.",
    command: "privilege::debug -> sekurlsa::logonpasswords",
    tags: ["LSASS Dump", "Pass the Hash", "Golden Ticket", "Active Directory"],
    officialUrl: "https://github.com/gentilkiwi/mimikatz",
    actionText: "Mimikatz Repo",
    level: "Advanced",
    details: "Fundamental utility for red teamers demonstrating credential caching flaws and executing Pass-the-Hash and Kerberos ticket forgery."
  },
  {
    id: "tool-autopsy",
    name: "Autopsy Digital Forensics",
    domain: "DIGITAL FORENSICS",
    icon: "fa-magnifying-glass-chart",
    desc: "Premier open-source digital forensics platform and graphical interface to The Sleuth Kit. Analyze hard drive images, memory, and smartphone dumps.",
    command: "E01 / Raw DD Image Ingestion & Timeline Analysis",
    tags: ["Hard Drive Forensics", "Timeline Analysis", "Deleted File Recovery", "DFIR"],
    officialUrl: "https://www.autopsy.com/download/",
    actionText: "Download Autopsy",
    level: "Intermediate",
    details: "Used by law enforcement, military, and corporate forensic examiners to investigate compromised systems and extract digital artifacts."
  },
  {
    id: "tool-volatility",
    name: "Volatility 3 Memory Forensics",
    domain: "RAM FORENSICS",
    icon: "fa-memory",
    desc: "World's most advanced framework for volatile memory (RAM) artifact extraction. Detects hidden processes, injected DLLs, and rootkits.",
    command: "python3 vol.py -f memdump.raw windows.pstree",
    tags: ["RAM Analysis", "Rootkit Detection", "Volatility 3", "Incident Response"],
    officialUrl: "https://github.com/volatilityfoundation/volatility3",
    actionText: "Volatility 3 Repo",
    level: "Intermediate / Pro",
    details: "Supports memory images from Windows, Linux, and macOS across 32-bit and 64-bit architectures."
  },
  {
    id: "tool-aircrack",
    name: "Aircrack-ng Wireless Suite",
    domain: "WIRELESS SECURITY",
    icon: "fa-wifi",
    desc: "Complete suite of utilities to assess Wi-Fi network security: packet capture, injection attacks, WPA/WPA2-PSK handshake capture, and dictionary cracking.",
    command: "airmon-ng start wlan0 && airodump-ng wlan0mon",
    tags: ["WiFi Security", "802.11", "WPA2 Handshake", "Packet Injection"],
    officialUrl: "https://www.aircrack-ng.org/",
    actionText: "Get Aircrack-ng",
    level: "Intermediate",
    details: "Includes airmon-ng, airodump-ng, aireplay-ng, and aircrack-ng for comprehensive wireless auditing."
  },
  {
    id: "tool-owasp-zap",
    name: "OWASP ZAP (Zed Attack Proxy)",
    domain: "OPEN SOURCE DAST",
    icon: "fa-bolt",
    desc: "The world's most widely used free and open-source web application security scanner maintained by the international software security community.",
    command: "zap.sh -daemon -port 8080",
    tags: ["DAST", "Automated Scanner", "OWASP", "Open Source Proxy"],
    officialUrl: "https://www.zaproxy.org/download/",
    actionText: "Download OWASP ZAP",
    level: "All Levels",
    details: "Ideal for automated CI/CD security integration, baseline spidering, active scanning, and REST API vulnerability discovery."
  }
];

var CYBER_OS = [
  {
    id: "os-kali",
    name: "Kali Linux 2026",
    type: "OFFENSIVE OS",
    icon: "fa-linux",
    desc: "The premier Debian-based penetration testing distribution equipped with over 600+ pre-installed security testing, reverse engineering, and forensics tools.",
    credentials: { username: "kali", password: "kali" },
    code: "sudo apt update && sudo apt dist-upgrade -y",
    tags: ["Offensive Security", "Penetration Testing", "Debian", "VirtualBox / VMware"],
    officialUrl: "https://www.kali.org/get-kali/",
    actionText: "Download Kali ISO",
    level: "Beginner to Pro",
    details: "Official Kali Linux download repository. Supported on Bare Metal, Virtual Machines (VMware, VirtualBox), WSL2, and Raspberry Pi. Default credentials: kali / kali."
  },
  {
    id: "os-parrot",
    name: "Parrot Security OS",
    type: "SECURITY & PRIVACY OS",
    icon: "fa-shield-halved",
    desc: "A lightweight, hardened operating system designed for ethical hackers, penetration testers, and digital privacy enthusiasts.",
    credentials: { username: "parrot", password: "parrot" },
    code: "sudo parrot-upgrade",
    tags: ["Lightweight", "Privacy", "Debian Core", "Hardened Kernel", "Anonsurf"],
    officialUrl: "https://parrotsec.org/download/",
    actionText: "Get Parrot OS",
    level: "All Levels",
    details: "Parrot Security provides a complete portable laboratory for cybersecurity operations, software development, and digital privacy defenses with pre-integrated Anonsurf."
  },
  {
    id: "os-remnux",
    name: "REMnux Malware Analysis OS",
    type: "FORENSICS & RE",
    icon: "fa-virus-slash",
    desc: "A Linux toolkit for reverse-engineering and analyzing malicious software, memory forensics, and document inspection curated by Lenny Zeltser.",
    credentials: { username: "remnux", password: "malware" },
    code: "remnux update",
    tags: ["Malware Analysis", "Reverse Engineering", "Memory Forensics", "SOC L2/L3"],
    officialUrl: "https://remnux.org/",
    actionText: "Download REMnux",
    level: "Intermediate / Pro",
    details: "Preconfigured with Ghidra, Cutter, Volatility, YARA, Wireshark, and static/dynamic malware disassemblers."
  },
  {
    id: "os-blackarch",
    name: "BlackArch Linux",
    type: "ELITE ARSENAL",
    icon: "fa-terminal",
    desc: "An Arch Linux-based penetration testing distribution containing an expansive arsenal of over 2,800+ specialized security tools.",
    credentials: { username: "root", password: "blackarch" },
    code: "pacman -Syu && pacman -S blackarch",
    tags: ["Arch Linux", "2800+ Tools", "Lightweight Window Managers", "Hardcore"],
    officialUrl: "https://blackarch.org/downloads.html",
    actionText: "Get BlackArch",
    level: "Advanced",
    details: "Designed specifically for elite security researchers and red team operators. Can be installed directly over existing Arch Linux installations."
  },
  {
    id: "os-tails",
    name: "Tails OS (Amnesic Incognito)",
    type: "PRIVACY & ANONYMITY",
    icon: "fa-mask",
    desc: "A portable live operating system that protects against surveillance and censorship by forcing all outgoing traffic through the Tor network.",
    credentials: { username: "amnesia", password: "(disabled)" },
    code: "Live USB Bootable • Amnesic RAM-only",
    tags: ["Tor Network", "Amnesic", "Cryptographic Tools", "Whistleblower Safe"],
    officialUrl: "https://tails.net/install/",
    actionText: "Download Tails",
    level: "All Levels",
    details: "Leaves no digital traces on the computer you use unless explicitly instructed. Runs entirely in RAM and shuts down cleanly."
  },
  {
    id: "os-commando",
    name: "Commando VM (Mandiant)",
    type: "WINDOWS PENTEST",
    icon: "fa-windows",
    desc: "Mandiant's Windows-based Automated Penetration Testing distribution customized for Active Directory assessment and red teaming.",
    credentials: { username: "Windows Admin", password: "User Set" },
    code: "powershell -exec bypass boxstarter.bat",
    tags: ["Active Directory", "Windows Red Teaming", "Mandiant", "BloodHound"],
    officialUrl: "https://github.com/mandiant/commando-vm",
    actionText: "Commando VM Repo",
    level: "Intermediate / Pro",
    details: "Includes 140+ native Windows attack tools such as Mimikatz, BloodHound, PowerView, SharpHound, and Burp Suite."
  },
  {
    id: "os-qubes",
    name: "Qubes OS (Reasonably Secure OS)",
    type: "ISOLATION HYPERVISOR",
    icon: "fa-cube",
    desc: "Security-oriented operating system leveraging Xen hypervisor virtualization to isolate user activities into separate, secure qubes (virtual domains).",
    credentials: { username: "user", password: "User Set" },
    code: "Xen Microkernel Isolation • AppVMs",
    tags: ["Xen Hypervisor", "Compartmentalization", "NSA Grade", "Whonix"],
    officialUrl: "https://www.qubes-os.org/downloads/",
    actionText: "Download Qubes ISO",
    level: "Advanced",
    details: "Used by Edward Snowden and security architects to isolate browser, work, email, and untrusted USB hardware into separate virtual machines."
  },
  {
    id: "os-flare-vm",
    name: "FLARE VM (Mandiant)",
    type: "WINDOWS REVERSE ENG",
    icon: "fa-bug-slash",
    desc: "A fully configured Windows-based reverse engineering, malware analysis, and incident response environment maintained by Google / Mandiant.",
    credentials: { username: "Windows Admin", password: "User Set" },
    code: "Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force",
    tags: ["Reverse Engineering", "x64dbg", "IDA Pro Ready", "Mandiant FLARE"],
    officialUrl: "https://github.com/mandiant/flare-vm",
    actionText: "FLARE VM Repo",
    level: "Intermediate / Advanced",
    details: "Packed with debuggers, disassemblers, decompilers, static analysis tools, network simulators, and forensic utilities."
  },
  {
    id: "os-csi-linux",
    name: "CSI Linux OS",
    type: "OSINT & INVESTIGATION",
    icon: "fa-magnifying-glass",
    desc: "An all-in-one cyber investigator distribution focused on Open Source Intelligence (OSINT), dark web investigations, digital forensics, and threat hunting.",
    credentials: { username: "csi", password: "csi" },
    code: "csi-updater",
    tags: ["OSINT", "Dark Web", "Digital Forensics", "Maltego", "Investigator"],
    officialUrl: "https://csilinux.com/",
    actionText: "Get CSI Linux",
    level: "All Levels",
    details: "Equipped with specialized tools for social media intelligence, dark web monitoring, image reverse search, and legal chain of custody."
  }
];

var CYBER_BOOKS = [
  {
    id: "book-wahh",
    title: "Web Application Hacker's Handbook (WAHH)",
    topic: "REFERENCE BIBLE",
    icon: "fa-book",
    desc: "The definitive guide by Dafydd Stuttard & Marcus Pinto detailing methodologies for finding and exploiting security flaws in web applications.",
    author: "Dafydd Stuttard & Marcus Pinto",
    tags: ["Web Security", "Exploit Methodology", "OWASP", "Must Read"],
    pdfUrl: "https://portswigger.net/web-security",
    actionText: "Access Web Security Academy",
    level: "Beginner to Pro"
  },
  {
    id: "book-rtfm",
    title: "RTFM: Red Team Field Manual",
    topic: "OPERATOR COMMANDS",
    icon: "fa-book-bookmark",
    desc: "A compact command-line reference guide containing syntax for Windows, Linux, Nmap, SQLmap, Metasploit, PowerShell, and privilege escalation.",
    author: "Ben Clark",
    tags: ["Red Teaming", "Command Syntax", "Quick Reference", "Tactical"],
    pdfUrl: "https://github.com/coreb1t/awesome-pentest-cheat-sheets",
    actionText: "View Command Guides",
    level: "All Levels"
  },
  {
    id: "book-bthm",
    title: "Blue Team Handbook: Incident Response Edition",
    topic: "SOC INCIDENT RESPONSE",
    icon: "fa-shield-cat",
    desc: "The go-to operational guide for cybersecurity incident responders and SOC analysts covering containment, network analysis, and memory triage.",
    author: "Don Murdoch",
    tags: ["Blue Team", "Incident Response", "SOC Analyst", "NIST Framework"],
    pdfUrl: "https://csrc.nist.gov/publications/detail/sp/800-61/rev-2/final",
    actionText: "Read NIST SP 800-61 PDF",
    level: "Intermediate"
  },
  {
    id: "book-hacker-playbook-3",
    title: "The Hacker Playbook 3: Red Team Edition",
    topic: "ADVERSARY SIMULATION",
    icon: "fa-chess-knight",
    desc: "Focuses on real-world campaign simulation, setting up adversary infrastructure, Active Directory attacks, and evasion tradecraft.",
    author: "Peter Kim",
    tags: ["Red Team", "C2 Infrastructure", "Active Directory", "Lateral Movement"],
    pdfUrl: "https://github.com/mubix/post-exploitation",
    actionText: "Explore Tradecraft Notes",
    level: "Intermediate to Advanced"
  },
  {
    id: "book-linux-hackers",
    title: "Linux Basics for Hackers",
    topic: "FUNDAMENTALS",
    icon: "fa-book-open-reader",
    desc: "Learn command-line mastery, bash scripting, network configurations, file system permissions, and stealth techniques tailored for security.",
    author: "OccupyTheWeb",
    tags: ["Linux", "Bash Scripting", "Fundamentals", "Essential"],
    pdfUrl: "https://www.linux.org/",
    actionText: "Linux Documentation",
    level: "Beginner"
  },
  {
    id: "book-practical-malware",
    title: "Practical Malware Analysis",
    topic: "REVERSE ENGINEERING",
    icon: "fa-virus",
    desc: "The definitive hands-on guide to dissecting malicious software, understanding assembly language, decompiling code, and debugging binaries.",
    author: "Michael Sikorski & Andrew Honig",
    tags: ["Malware", "x86 Assembly", "Disassembly", "IDA Pro", "Sandboxes"],
    pdfUrl: "https://nostarch.com/malware",
    actionText: "Malware Labs Index",
    level: "Intermediate to Advanced"
  },
  {
    id: "book-black-hat-python",
    title: "Black Hat Python: Python for Hackers & Pentesters",
    topic: "OFFENSIVE SCRIPTING",
    icon: "fa-brands fa-python",
    desc: "Learn how to write network sniffers, build custom Trojan command-and-control backdoors, manipulate packets, and escalate privileges with Python.",
    author: "Justin Seitz & Tim Arnold",
    tags: ["Python", "Scapy", "Trojan Design", "Network Sniffing", "Exploit Dev"],
    pdfUrl: "https://github.com/tiarno/black-hat-python",
    actionText: "Source Code Repository",
    level: "Intermediate"
  },
  {
    id: "book-operator-handbook",
    title: "Operator Handbook: Red Team + Blue Team",
    topic: "DUAL DISCIPLINE",
    icon: "fa-terminal",
    desc: "Comprehensive tactical reference covering both offensive techniques and defensive mitigations across cloud, network, and endpoint vectors.",
    author: "Joshua Picon & Craig Hays",
    tags: ["Red & Blue", "Cheat Sheets", "Cloud Auditing", "Hardening"],
    pdfUrl: "https://attack.mitre.org/",
    actionText: "MITRE ATT&CK Matrix",
    level: "All Levels"
  },
  {
    id: "book-owasp-top10",
    title: "OWASP Top 10 Official Documentation",
    topic: "STANDARD COMPLIANCE",
    icon: "fa-file-pdf",
    desc: "The globally recognized consensus standard regarding the most critical security risks to web applications with remediation guides.",
    author: "OWASP Foundation",
    tags: ["OWASP Top 10", "Remediation", "Code Review", "AppSec"],
    pdfUrl: "https://owasp.org/www-project-top-ten/",
    actionText: "Download OWASP PDF",
    level: "All Levels"
  },
  {
    id: "book-tangled-web",
    title: "The Tangled Web: Securing Modern Web Applications",
    topic: "BROWSER SECURITY",
    icon: "fa-globe",
    desc: "Detailed security analysis of web browser security models, same-origin policies, DOM interactions, and sandbox boundaries.",
    author: "Michal Zalewski (lcamtuf)",
    tags: ["Browser Security", "Same-Origin Policy", "DOM", "Web Architecture"],
    pdfUrl: "https://nostarch.com/tangledweb",
    actionText: "Reference Guide",
    level: "Intermediate / Advanced"
  }
];

if (typeof window !== 'undefined') {
  window.CYBER_COURSES = CYBER_COURSES;
  window.CYBER_TOOLS = CYBER_TOOLS;
  window.CYBER_OS = CYBER_OS;
  window.CYBER_BOOKS = CYBER_BOOKS;
}
